Repository DataKind-DC/capital-nature-ingest, pull requests merged in 2019-03, with the labels that each got.

#70 FIX: get event dates/times for Fairfax Events (#69)
  events/fairfax.py
  tests/fairfax_test.py
  tests/fixtures/fairfax_test_fixtures.py
Labels: fix

#73 FIX: Empty venue fix
  events/ans.py
  events/arlington.py
  events/casey_trees.py
  events/city_blossoms.py
  events/dug_network.py
  events/fairfax.py
  events/montgomery.py
  events/nps.py
  events/sierra_club.py
  events/vnps.py
  tests/fixtures/montgomery_test_fixtures.py
  tests/fixtures/sierra_club_test_fixtures.py
  tests/sierra_club_test.py
Labels: fix

#82 FIX: don't capture events w/o times (#75)
  events/montgomery.py
Labels: fix

#83 FIX: get event descriptions from vnps event pages (#80)
  events/vnps.py
  tests/fixtures/vnps_test_fixtures.py
  tests/vnps_test.py
Labels: fix

#84 FIX: get missing NPS event descriptions (#80)
  events/nps.py
  tests/nps_test.py
Labels: fix

#86 ENH: prepend event descriptions with state (#77)
  get_events.py
  requirements.txt
Labels: enhancement, question

#87 Filtering events with only start time
  events/dug_network.py
Labels: fix

#62 Create tnc.py
  events/tnc.py
Labels: enhancement

#89 TST: add tests for TNC
  events/tnc.py
  get_events.py
  tests/fixtures/tnc_test_fixtures.py
  tests/tnc_test.py
Labels: enhancement, test

#90 ENH: add loggers
  events/ans.py
  events/arlington.py
  events/casey_trees.py
  events/city_blossoms.py
  events/dug_network.py
  events/fairfax.py
  events/montgomery.py
  events/nps.py
  events/sierra_club.py
  events/tnc.py
  events/vnps.py
  get_events.py
  requirements.txt
  tests/fixtures/nps_test_fixtures.py
  tests/montgomery_test.py
Labels: enhancement
