Repository DataKind-DC/capital-nature-ingest, pull requests merged in 2020-02, with the labels that each got.

#200 TST: add linting
  .circleci/config.yml
  .github/CONTRIBUTING.md
  events/ans.py
  events/arlington.py
  events/aws.py
  events/casey_trees.py
  events/city_blossoms.py
  events/dc_audubon.py
  events/eleventh_street.py
  events/fairfax.py
  events/fona.py
  events/friends_of_kenilworth_gardens.py
  events/loudoun_wildlife_conservancy.py
  events/montgomery.py
  events/nova_parks.py
  events/nps.py
  events/nva_audubon_society.py
  events/potomac_conservancy.py
  events/rcc.py
  events/riverkeeper.py
  events/sierra_club.py
  events/sierra_club_md.py
  events/tnc.py
  events/us_botanic_garden.py
  events/vnps.py
  get_events.py
  requirements.txt
  tox.ini
  utils/reports.py
Labels: test

#203 FIX: filter out distant venues (#106)
  events/nps.py
Labels: fix

#204 FIX: rename/refactor eventbrite sources and tests (#175)
  .circleci/config.yml
  .github/CONTRIBUTING.md
  .github/STYLE-GUIDE.md
  events/ans.py
  events/arlington.py
  events/aws.py
  events/casey_trees.py
  events/dc_audubon.py
  events/eleventh_street.py
  events/fairfax.py
  events/fona.py
  events/fona_reworked.py
  events/friends_of_kenilworth_gardens.py
  events/friends_of_kenilworth_gardens_reworked.py
  events/loudoun_wildlife_conservancy.py
  events/montgomery.py
  events/nova_parks.py
  events/nova_parks_reworked.py
  events/nps.py
  events/nva_audubon_society.py
  events/potomac_conservancy.py
  events/rcc.py
  events/riverkeeper.py
  events/riverkeeper_reworked.py
  events/sierra_club.py
  events/sierra_club_md.py
  events/sierra_club_md_reworked.py
  events/tnc.py
  events/us_botanic_garden.py
  events/vnps.py
  get_events.py
  log.py
  tests/fona_reworked_test.py
  tests/friends_reworked_test.py
  tests/nova_parks_reworked_test.py
  tests/riverkeeper_reworked_test.py
  tests/sierra_club_md_reworked_test.py
  utils/event_source_map.py
  utils/formatters.py
  utils/reports.py
Labels: fix

#206 PERF: Use multithreading
  events/potomac_conservancy.py
  get_events.py
Labels: performance

#212 ENH: Deploy to AWS Lambda
  .github/CONTRIBUTING.md
  .gitignore
  Dockerfile
  README.md
  app.py
  aws/README.md
  build.sh
  cdk.json
  event_schema.md
  events/ans.py
  events/arlington.py
  events/aws.py
  events/casey_trees.py
  events/city_blossoms.py
  events/dc_audubon.py
  events/eleventh_street.py
  events/fairfax.py
  events/fona.py
  events/friends_of_kenilworth_gardens.py
  events/loudoun_wildlife_conservancy.py
  events/montgomery.py
  events/nova_parks.py
  events/nps.py
  events/nva_audubon_society.py
  events/potomac_conservancy.py
  events/rcc.py
  events/riverkeeper.py
  events/sierra_club.py
  events/sierra_club_md.py
  events/tnc.py
  events/us_botanic_garden.py
  events/utils/aws_utils.py
  events/utils/event_source_map.py
  events/utils/formatters.py
  events/utils/log.py
  events/utils/reports.py
  events/vnps.py
  get_events.py
  lambda-requirements.txt
  requirements.txt
  tests/formatters_test.py
  tests/utils.py
  utils/reports.py
Labels: AWS, enhancement

#216 FIX: ignore long multi-day events #210
  events/montgomery.py
Labels: fix

#219 FIX: handle recurring events :bug:
  events/eleventh_street.py
Labels: fix

#224 FIX: handle case where categories are missing
  events/casey_trees.py
Labels: fix

#220 ENH: MD native society scraper
  events/mdflora.py
  events/utils/event_source_map.py
  get_events.py
  tests/mdflora_test.py
Labels: enhancement, new event source
